FROM crawforc3/raspberrypi-uwsgi-nginx-flask:latest
WORKDIR /BatteryTester
ENV STATIC_URL /static
ENV STATIC_PATH /BatteryTester/app/static
ADD requirements.txt /BatteryTester
ADD main.py /BatteryTester
ADD config.py /BatteryTester
ADD uwsgi.ini /BatteryTester
COPY ./app /BatteryTester/app
# # Install the dependencies
RUN pip install -r requirements.txt

# run the command to start uWSGI
# CMD ["uwsgi", "uwsgi.ini"]